spring.h2.console.enabled=true
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.initialization-mode=always
spring.datasource.initialize=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none 
application.version=1.0
application.title=Accounts

server:
        port: 7777
spring:
        datasource: jdbc:h2:mem:accounts
        username: sa
        password: 
        initialization-mode: always
        initialize: true
                
